### ISSUE TITLE
Unify install_t10ns() and update_t10ns() methods

### ISSUE THREAD

**Issue by tyrann0us** [pelmered/composer-plugin-language-update#4]
[`install_t10ns()`](https://github.com/pelmered/composer-plugin-language-update/blob/master/src/PostUpdateLanguageUpdate.php#L37-L53) and [`update_t10ns()`](https://github.com/pelmered/composer-plugin-language-update/blob/master/src/PostUpdateLanguageUpdate.php#L65-L81) have almost identical function bodies. IMO they should be merged in one method (with a conditional check what hook the method is currently added to).
This would allow users to add the same function call to both the install and update hook, or use a [referenced script](https://getcomposer.org/doc/articles/scripts.md#referencing-scripts) like it's used in [WP Starter](https://github.com/dnaber-de/wpstarter-boilerplate)'s [`composer.json`](https://github.com/dnaber-de/wpstarter-boilerplate/blob/master/composer.json#L13-L19).

**Comment by pelmered** [comment]
Yes, this is a good idea. I noticed same when I read the code, but I didn't want to change the API at that time. But now I agree. It would be much better with a single method. 
I guess you can check what event you are on with the PackageEvent object, but I haven't done any research about that. 

A referenced script is a great idea.

**Comment by pelmered** [comment]
This is now implemented.
